"""add mascot_settings table

Revision ID: 76c4c340b706
Revises: 1a13359f9afa
Create Date: 2026-05-08 22:39:00.463178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c4c340b706'
down_revision: Union[str, Sequence[str], None] = '1a13359f9afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mascot_visible', sa.Boolean(), nullable=False),
    sa.Column('mascot_scale', sa.Float(), nullable=False),
    sa.Column('mascot_position_x', sa.Integer(), nullable=True),
    sa.Column('mascot_position_y', sa.Integer(), nullable=True),
    sa.Column('show_on_mobile', sa.Boolean(), nullable=False),
    sa.Column('greeting_enabled', sa.Boolean(), nullable=False),
    sa.Column('greeting_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('random_action_interval', sa.Integer(), nullable=False),
    sa.Column('context_aware', sa.Boolean(), nullable=False),
    sa.Column('drag_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mascot_settings_id'), 'mascot_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mascot_settings_id'), table_name='mascot_settings')
    op.drop_table('mascot_settings')
    # ### end Alembic commands ###
